### PR TITLE
Pr mag

### PR DESCRIPTION
**Pull request by hippo5329**
Please pull the updates for magnetometer devices support.

Best regards,
Thomas Chou

### CODE REVIEW

**Comment by hippo5329** [comment]
ak8963 in mp9250 from i2cdevlib does not work. please wait for the fix.

**Comment by hippo5329** [comment]
Problem resolved. Tested on hardware: AK8963 of MPU9250, AK09918, QMC5883L.
Please pull. Thanks.

**Comment by hippo5329** [comment]
Also tested on hardware, ak8975 of mpu9150.

**Comment by grassjelly** [comment]
@hippo5329 thank you!

**Pull request merged**
