### PR TITLE
Fix Foxy Firmware and Integrate with CI

### PR DESCRIPTION
**Pull request by atticusrussell**
This fixes the issues with building ROS Foxy firmware, encountered in issue #35 and adds CI to the branch to prove it and integrates with the CI in PR #45, which can be read for details on the CI implementation.

* Revert "revert back to micro_ros_arduino for foxy branch"
* Add CI firmware building to foxy branch
* Specify micro_ros_platformio as version with foxy support
* add micro_ros_utilities as lib_dep
* manually add typesupport library

### CODE REVIEW

**Comment by grassjelly** [comment]
could we pull the type support library somewhere instead?

**Comment by atticusrussell** [comment]
> could we pull the type support library somewhere instead?

I'll look into it

**Comment by grassjelly** [comment]
I'm okay to fork the specific commit on a separate repo, just let me know which one. Thanks!

**Comment by atticusrussell** [comment]
> I'm okay to fork the specific commit on a separate repo, just let me know which one. Thanks!

It looks like it may be this folder in the rosidl repo, but I made that commit a month ago and the changelogs are different, so will have to verify:
https://github.com/ros2/rosidl/tree/rolling/rosidl_typesupport_introspection_c

If I recall correctly, I think I just copied the source because I didn't wish to build all the folders in the [rosidl](https://github.com/ros2/rosidl) repo, which I believe happened when I added that repo as a libdep. Not 100% confident in that recollection though. 

Maybe fork that repo, naming yours rosidl_typesupport_introspection_c and delete all other modules in it and move the contents of the rosidl_typesupport_introspection_c directory to the repo root?

**Comment by grassjelly** [comment]
that could work, and just link it to that forked repo as libdep something like this https://github.com/linorobot/linorobot2_hardware/blob/galactic/firmware/platformio.ini#L17

**Comment by atticusrussell** [comment]
Yeah. Also I realized why the changelogs are different: I copied the code from their `foxy` branch but was looking at `rolling`.

In the `linorobot/rosidl_typesupport_introspection_c` fork of `ros2/rosidl` it might make sense to fork all branches (for future needs), and then we can just specify the desired branch in the libdep section of `platformio.ini`

**Comment by atticusrussell** [comment]
@grassjelly I got it working. If you want to fork [my fork](https://github.com/atticusrussell/rosidl_typesupport_introspection_c/tree/remove-non-tsic-foxy) using the linorobot GitHub organization (all branches, but FYI my modifications are on foxy-tsic-only), I'll point the libdep there and merge the change here

**Comment by grassjelly** [comment]
here's the fork https://github.com/linorobot/rosidl_typesupport_introspection_c

**Comment by atticusrussell** [comment]
Done! :tada:

**Comment by atticusrussell** [comment]
@grassjelly this should be good to be merged!

**Comment by grassjelly** [comment]
thanks @atticusrussell

**Pull request merged**
